[package]
name = "rust"
version = "0.0.0"
build = "build.rs"
edition = "2021"

[lib]
path = "rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24.6"
base64 = "0.21.2"
clipboard-win = "4.5.0"

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_FileSystem",
    "Win32_System_SystemInformation",
    "Win32_System_Environment",
    "Win32_UI_Input_Ime",
    "Win32_Globalization",
]

[build-dependencies]
napi-build = "2"
static_vcruntime = "2.0"
